#ifndef CEDAR_CABI_H
#define CEDAR_CABI_H

/* Generated by cbindgen from cedar-cabi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* CEDAR_CABI_H */
