#ifndef CEDAR_CABI_H
#define CEDAR_CABI_H

/* Generated by cbindgen from cedar-cabi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes for the C ABI. Fail-closed: only a clean Cedar `Decision::Allow`
 * (resp. a passing validation) yields `Allow`/`Valid`.
 */
enum CedarResult
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  Deny = 0,
  Allow = 1,
  Valid = 2,
  Invalid = 3,
  Error = -1,
};
#ifndef __cplusplus
typedef int32_t CedarResult;
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a string previously returned by this library. Null is a safe no-op.
 *
 * # Safety
 * `s` must be a pointer returned by a `cedar-cabi` function and not freed before.
 */
void cedar_string_free(char *s);

/**
 * Authorize one request. Fail-closed: returns `Allow` (1) ONLY on a clean
 * Cedar `Decision::Allow`; `Deny` (0) on a clean deny (reasons/errors in
 * `*out_diag`); `Error` (-1) on any null arg, parse/validation/eval failure,
 * or panic (message in `*out_diag`). The non-Allow diagnostics string lets the
 * caller log + emit a reason-labeled metric (spec §6 inv.7; §7 "engine error
 * => deny, never pass-through"). `context_json` is a JSON object (`{}` = none);
 * `entities_json` is a JSON array (`[]` = none).
 *
 * # Safety
 * All pointers must be valid NUL-terminated C strings (or null, which is a
 * fail-closed Error). `out_diag` must be a valid pointer to a writable pointer.
 */
CedarResult cedar_is_authorized(const char *policies,
                                const char *principal,
                                const char *action,
                                const char *resource,
                                const char *context_json,
                                const char *entities_json,
                                char **out_diag);

/**
 * Validate a Cedar policy set against a schema (registration-time gate).
 * Fail-closed: `Valid` (2) ONLY when validation passes cleanly; `Invalid` (3)
 * with the validation errors in `*out_diag`; `Error` (-1) on null args, an
 * unparseable schema/policy, or a panic (message in `*out_diag`). The non-Valid
 * diagnostics string lets the caller log + emit a reason-labeled metric
 * (spec §6 inv.7). `schema_src` is Cedar human schema syntax (`.cedarschema`).
 *
 * # Safety
 * Pointers must be valid NUL-terminated C strings (or null => Error).
 * `out_diag` must point to a writable pointer.
 */
CedarResult cedar_validate(const char *schema_src, const char *policies_src, char **out_diag);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CEDAR_CABI_H */
