#ifndef CEDAR_CABI_H
#define CEDAR_CABI_H

/* Generated by cbindgen from cedar-cabi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a string previously returned by this library. Null is a safe no-op.
 *
 * # Safety
 * `s` must be a pointer returned by a `cedar-cabi` function and not freed before.
 */
void cedar_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CEDAR_CABI_H */
